// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.crmco.crm.model;

import com.crmco.crm.model.ZipCode;
import com.crmco.crm.model.ZipCodeDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect ZipCodeDataOnDemand_Roo_DataOnDemand {
    
    declare @type: ZipCodeDataOnDemand: @Component;
    
    private Random ZipCodeDataOnDemand.rnd = new SecureRandom();
    
    private List<ZipCode> ZipCodeDataOnDemand.data;
    
    public ZipCode ZipCodeDataOnDemand.getNewTransientZipCode(int index) {
        ZipCode obj = new ZipCode();
        setCode(obj, index);
        return obj;
    }
    
    public void ZipCodeDataOnDemand.setCode(ZipCode obj, int index) {
        String code = "code_" + index;
        obj.setCode(code);
    }
    
    public ZipCode ZipCodeDataOnDemand.getSpecificZipCode(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        ZipCode obj = data.get(index);
        Long id = obj.getId();
        return ZipCode.findZipCode(id);
    }
    
    public ZipCode ZipCodeDataOnDemand.getRandomZipCode() {
        init();
        ZipCode obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return ZipCode.findZipCode(id);
    }
    
    public boolean ZipCodeDataOnDemand.modifyZipCode(ZipCode obj) {
        return false;
    }
    
    public void ZipCodeDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = ZipCode.findZipCodeEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'ZipCode' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<ZipCode>();
        for (int i = 0; i < 10; i++) {
            ZipCode obj = getNewTransientZipCode(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
