// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.crmco.crm.model;

import com.crmco.crm.model.ZipCode;
import com.crmco.crm.model.ZipCodeDataOnDemand;
import com.crmco.crm.model.ZipCodeIntegrationTest;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect ZipCodeIntegrationTest_Roo_IntegrationTest {
    
    declare @type: ZipCodeIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: ZipCodeIntegrationTest: @Transactional;
    
    @Autowired
    private ZipCodeDataOnDemand ZipCodeIntegrationTest.dod;
    
    @Test
    public void ZipCodeIntegrationTest.testCountZipCodes() {
        Assert.assertNotNull("Data on demand for 'ZipCode' failed to initialize correctly", dod.getRandomZipCode());
        long count = ZipCode.countZipCodes();
        Assert.assertTrue("Counter for 'ZipCode' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void ZipCodeIntegrationTest.testFindZipCode() {
        ZipCode obj = dod.getRandomZipCode();
        Assert.assertNotNull("Data on demand for 'ZipCode' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ZipCode' failed to provide an identifier", id);
        obj = ZipCode.findZipCode(id);
        Assert.assertNotNull("Find method for 'ZipCode' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'ZipCode' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void ZipCodeIntegrationTest.testFindAllZipCodes() {
        Assert.assertNotNull("Data on demand for 'ZipCode' failed to initialize correctly", dod.getRandomZipCode());
        long count = ZipCode.countZipCodes();
        Assert.assertTrue("Too expensive to perform a find all test for 'ZipCode', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<ZipCode> result = ZipCode.findAllZipCodes();
        Assert.assertNotNull("Find all method for 'ZipCode' illegally returned null", result);
        Assert.assertTrue("Find all method for 'ZipCode' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void ZipCodeIntegrationTest.testFindZipCodeEntries() {
        Assert.assertNotNull("Data on demand for 'ZipCode' failed to initialize correctly", dod.getRandomZipCode());
        long count = ZipCode.countZipCodes();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<ZipCode> result = ZipCode.findZipCodeEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'ZipCode' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'ZipCode' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void ZipCodeIntegrationTest.testFlush() {
        ZipCode obj = dod.getRandomZipCode();
        Assert.assertNotNull("Data on demand for 'ZipCode' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ZipCode' failed to provide an identifier", id);
        obj = ZipCode.findZipCode(id);
        Assert.assertNotNull("Find method for 'ZipCode' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyZipCode(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'ZipCode' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ZipCodeIntegrationTest.testMergeUpdate() {
        ZipCode obj = dod.getRandomZipCode();
        Assert.assertNotNull("Data on demand for 'ZipCode' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ZipCode' failed to provide an identifier", id);
        obj = ZipCode.findZipCode(id);
        boolean modified =  dod.modifyZipCode(obj);
        Integer currentVersion = obj.getVersion();
        ZipCode merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'ZipCode' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ZipCodeIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'ZipCode' failed to initialize correctly", dod.getRandomZipCode());
        ZipCode obj = dod.getNewTransientZipCode(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'ZipCode' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'ZipCode' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'ZipCode' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void ZipCodeIntegrationTest.testRemove() {
        ZipCode obj = dod.getRandomZipCode();
        Assert.assertNotNull("Data on demand for 'ZipCode' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ZipCode' failed to provide an identifier", id);
        obj = ZipCode.findZipCode(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'ZipCode' with identifier '" + id + "'", ZipCode.findZipCode(id));
    }
    
}
