// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.crmco.crm.model;

import com.crmco.crm.model.Customer;

privileged aspect Customer_Roo_JavaBean {
    
    public String Customer.getFirstName() {
        return this.firstName;
    }
    
    public void Customer.setFirstName(String firstName) {
        this.firstName = firstName;
    }
    
}
