// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.crmco.crm.model;

import com.crmco.crm.model.Customer;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Customer_Roo_Configurable {
    
    declare @type: Customer: @Configurable;
    
}
