// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.crmco.crm.model;

import com.crmco.crm.model.ZipCode;

privileged aspect ZipCode_Roo_JavaBean {
    
    public String ZipCode.getCode() {
        return this.code;
    }
    
    public void ZipCode.setCode(String code) {
        this.code = code;
    }
    
}
