// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.crmco.crm.model;

import com.crmco.crm.model.ZipCode;
import java.util.List;
import javax.persistence.EntityManager;
import org.springframework.transaction.annotation.Transactional;

privileged aspect ZipCode_Roo_Jpa_ActiveRecord {
    
    public static final EntityManager ZipCode.entityManager() {
        EntityManager em = new ZipCode().entityManager;
        if (em == null) throw new IllegalStateException("Entity manager has not been injected (is the Spring Aspects JAR configured as an AJC/AJDT aspects library?)");
        return em;
    }
    
    public static long ZipCode.countZipCodes() {
        return entityManager().createQuery("SELECT COUNT(o) FROM ZipCode o", Long.class).getSingleResult();
    }
    
    public static List<ZipCode> ZipCode.findAllZipCodes() {
        return entityManager().createQuery("SELECT o FROM ZipCode o", ZipCode.class).getResultList();
    }
    
    public static ZipCode ZipCode.findZipCode(Long id) {
        if (id == null) return null;
        return entityManager().find(ZipCode.class, id);
    }
    
    public static List<ZipCode> ZipCode.findZipCodeEntries(int firstResult, int maxResults) {
        return entityManager().createQuery("SELECT o FROM ZipCode o", ZipCode.class).setFirstResult(firstResult).setMaxResults(maxResults).getResultList();
    }
    
    @Transactional
    public void ZipCode.persist() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.persist(this);
    }
    
    @Transactional
    public void ZipCode.remove() {
        if (this.entityManager == null) this.entityManager = entityManager();
        if (this.entityManager.contains(this)) {
            this.entityManager.remove(this);
        } else {
            ZipCode attached = ZipCode.findZipCode(this.id);
            this.entityManager.remove(attached);
        }
    }
    
    @Transactional
    public void ZipCode.flush() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.flush();
    }
    
    @Transactional
    public void ZipCode.clear() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.clear();
    }
    
    @Transactional
    public ZipCode ZipCode.merge() {
        if (this.entityManager == null) this.entityManager = entityManager();
        ZipCode merged = this.entityManager.merge(this);
        this.entityManager.flush();
        return merged;
    }
    
}
