// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.crmco.crm.model;

import com.crmco.crm.model.ZipCode;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Version;

privileged aspect ZipCode_Roo_Jpa_Entity {
    
    declare @type: ZipCode: @Entity;
    
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "id")
    private Long ZipCode.id;
    
    @Version
    @Column(name = "version")
    private Integer ZipCode.version;
    
    public Long ZipCode.getId() {
        return this.id;
    }
    
    public void ZipCode.setId(Long id) {
        this.id = id;
    }
    
    public Integer ZipCode.getVersion() {
        return this.version;
    }
    
    public void ZipCode.setVersion(Integer version) {
        this.version = version;
    }
    
}
